/**
 * Aqui van todos los encabezados para los diferentes reportes.
 */
export const userPerformanceColumns = [
  "User Name",
  "Email",
  "FirstName",
  "LastName",
  "Country",
  "Region",
  "Company Name",
  "Company Type",
  "Company Level",
  "Company Status",
  "User Role",
  "VIP Renewal CC (USD)",
  "VIP Renewal DC (USD)",
  "VIP New Business CC (USD)",
  "VIP New Business DC (USD)",
  "VMP Renewal CC (USD)",
  "VMP Renewal DC (USD)",
  "VMP New Business CC (USD)",
  "VMP New Business DC (USD)",
  "VIP Revenue Q1 (USD)",
  "VIP Revenue Q2 (USD)",
  "VIP Revenue Q3 (USD)",
  "VIP Revenue Q4 (USD)",
  "VMP Revenue Q1 (USD)",
  "VMP Revenue Q2 (USD)",
  "VMP Revenue Q3 (USD)",
  "VMP Revenue Q4 (USD)",
  "Revenue Q1 (USD)",
  "Revenue Q2 (USD)",
  "Revenue Q3 (USD)",
  "Revenue Q4 (USD)",
  "Total VIP Revenue (USD)",
  "Total VMP Revenue (USD)",
  "Actual Revenue (USD)",
  "RMA (USD)",
  "Sales DigiPoints",
  "Promotion DigiPoints",
  "Behavior DigiPoints",
  "Total DigiPoints",
  "DigiPoints Redeemed",
  "Total % effectiveness",
];

export const salesPerformanceColumns = [
  "Membership ID",
  "Company Name",
  "Region",
  "Country",
  "Company Type",
  "Company Level",
  "Company Status",
  "Company Active Users",
  "VIP Renewal CC (USD)",
  "VIP Renewal DC (USD)",
  "VIP New Business CC (USD)",
  "VIP New Business DC (USD)",
  "VMP Renewal CC (USD)",
  "VMP Renewal DC (USD)",
  "VMP New Business CC (USD)",
  "VMP New Business DC (USD)",
  "VIP Revenue Q1 (USD)",
  "VIP Revenue Q2 (USD)",
  "VIP Revenue Q3 (USD)",
  "VIP Revenue Q4 (USD)",
  "VMP Revenue Q1 (USD)",
  "VMP Revenue Q2 (USD)",
  "VMP Revenue Q3 (USD)",
  "VMP Revenue Q4 (USD)",
  "Revenue Q1 (USD)",
  "Revenue Q2 (USD)",
  "Revenue Q3 (USD)",
  "Revenue Q4 (USD)",
  "Total VIP Revenue (USD)",
  "Total VMP Revenue (USD)",
  "Actual Revenue (USD)",
  "RMA (USD)",
  "Total Revenue (USD)",
  "Expected Revenue (USD)",
  "Total % effectiveness",
];
